package com.plynexa.agent.core.events

import kotlinx.serialization.Serializable

@Serializable
enum class AgentEventType {
    AGENT_STATE_CHANGED,
    VOICE_WAKE, VOICE_TRANSCRIPT, VOICE_STARTED, VOICE_FINISHED,
    MESSAGE_RECEIVED, MESSAGE_CREATED, MESSAGE_PERSISTED,
    CONVERSATION_UPDATED, CONVERSATION_DELETED,
    CONTEXT_RESOLVING,
    MEMORY_SEARCH_STARTED, MEMORY_CREATED, MEMORY_UPDATED, MEMORY_DELETED, MEMORY_FOUND,
    ROUTE_SELECTED, RESPONSE_CREATED,
    TASK_CREATED, TASK_STARTED, TASK_PROGRESS, TASK_WAITING, TASK_COMPLETED, TASK_FAILED, TASK_CANCELLED,
    SKILL_EXECUTED, SKILL_FAILED,
    PROVIDER_SELECTED, PROVIDER_REQUEST, PROVIDER_RESPONSE, PROVIDER_ERROR,
    REMINDER_CREATED, REMINDER_UPDATED, REMINDER_DELETED, REMINDER_TRIGGERED,
    BACKUP_STARTED, BACKUP_COMPLETED, BACKUP_FAILED,
    DEVICE_CONNECTED, DEVICE_DISCONNECTED,
    SYNC_STARTED, SYNC_COMPLETED, SYNC_FAILED,
}

@Serializable
data class AgentEvent(
    val id: String,
    val type: AgentEventType,
    val timestampEpochMillis: Long,
    val correlationId: String? = null,
    val source: String,
    val metadata: Map<String, String> = emptyMap(),
)
